CREATE TABLE users (
    id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(60) UNIQUE NOT NULL,
    email VARCHAR(60) UNIQUE NOT NULL,
    password BINARY(60) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);